//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shouldly.Refactorings.MSTest {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shouldly.Refactorings.MSTest.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouldly.
        /// </summary>
        internal static string AssertAreEqualCategory {
            get {
                return ResourceManager.GetString("AssertAreEqualCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreEqual(expected, actual) should be replaced with actual.ShouldBeNull(expected).
        /// </summary>
        internal static string AssertAreEqualDescription {
            get {
                return ResourceManager.GetString("AssertAreEqualDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to a Shouldly assertion.
        /// </summary>
        internal static string AssertAreEqualFixText {
            get {
                return ResourceManager.GetString("AssertAreEqualFixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreEqual({0}, {1}) should be replaced with {0}.ShouldBeNull({1}).
        /// </summary>
        internal static string AssertAreEqualMessageFormat {
            get {
                return ResourceManager.GetString("AssertAreEqualMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.AreEqual(expected, actual) should be replaced with actual.ShouldBeNull(expected).
        /// </summary>
        internal static string AssertAreEqualTitle {
            get {
                return ResourceManager.GetString("AssertAreEqualTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouldly.
        /// </summary>
        internal static string AssertIsNullCategory {
            get {
                return ResourceManager.GetString("AssertIsNullCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsNull(value) should be replaced with value.ShouldBeNull().
        /// </summary>
        internal static string AssertIsNullDescription {
            get {
                return ResourceManager.GetString("AssertIsNullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to a Shouldly assertion.
        /// </summary>
        internal static string AssertIsNullFixText {
            get {
                return ResourceManager.GetString("AssertIsNullFixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsNull({0}) should be replaced with {0}.ShouldBeNull().
        /// </summary>
        internal static string AssertIsNullMessageFormat {
            get {
                return ResourceManager.GetString("AssertIsNullMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assert.IsNull(value) should be replaced with value.ShouldBeNull().
        /// </summary>
        internal static string AssertIsNullTitle {
            get {
                return ResourceManager.GetString("AssertIsNullTitle", resourceCulture);
            }
        }
    }
}
